### PR TITLE
Code cleanup + use cryptographically secure random for "key" generation

### PR DESCRIPTION
**Pull request by mattyokan**
Mostly things caught by automated inspections, also uses a proper cryptographically secure random number generator instead of ``java.util.Random`` which is clearly marked as *not cryptographically secure*. I did note in a comment that the entire function should ideally be replaced with an actual standard key generation algorithm, however, as a note for someone else (like the maintainer) to fix it.

### CODE REVIEW

**Comment by mattyokan** [comment]
I'd like to request a review from @penple

**Comment by heychazza** [comment]
Thank you for your time spent on this pull request, really appreciated.

**Review by Penple — APPROVED** [review]
LGTM!

**Review by jimuskin — COMMENTED** [review]
Interesting approach, LGTM

**Pull request merged**
